# version: 2
# updates:
#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "daily"
#       time: "15:"
#     versioning-strategy: widen

#   -   package-ecosystem: "composer"
#     # Files stored in repository root
#     directory: "/"
#     schedule:
#       interval: "daily"
#       time: "15:20"
#     versioning-strategy: widen

# name: Automation Tests
# on:
# workflow_dispatch:
# schedule:
#   - cron: '55 15 * * *'
#   - cron: '55 15 * * *'

# jobs:
#   ui-chrome-smoke-tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Smoke Test
#         uses: actions/checkout@v2
#         if: github.event.schedule == '50 15 * * *'
#         with:
#           # Run regression test suite
#           command: npm run smoke-test
#   ui-chrome-sanity-tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Sanity Test
#         uses: actions/checkout@v2
#         if: github.event.schedule != '50 15 * * *'
#         with:
#           # Run sanity test suite
#           command: npm run sanity-test
name: Daily-trigger
on:
  schedule:
    - cron: '50 9 * * *'
  pull_request:
    branches:
      - master
    types: [closed]
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: (github.event.schedule == '50 9 * * *')||(github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
