on:
  schedule:
    - cron: '0 */13 * * *'
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule == '0 */13 * * *'
        run: echo "This step will be skipped on Monday and Thursday"
      - name: Every time
        run: echo "This step will always run"
