name: Build Android
on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run:  npm install --legacy-peer-deps
    
  build-android:
    needs: install
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install --legacy-peer-deps
      - name: Build Android Release
        run: 
          cd android && ./gradlew assembleRelease
